#pragma once

#include <string_view>

namespace tssb {

enum class SingleIndicatorId {
    RSI,
    DetrendedRsi,
    Stochastic,
    StochasticRsi,
    MovingAverageDifference,
    Macd,
    Ppo,
    LinearTrend,
    QuadraticTrend,
    CubicTrend,
    PriceIntensity,
    Adx,
    AroonUp,
    AroonDown,
    AroonDiff,
    CloseMinusMovingAverage,
    LinearDeviation,
    QuadraticDeviation,
    CubicDeviation,
    PriceChangeOscillator,
    PriceVarianceRatio,
    ChangeVarianceRatio,
    BollingerWidth,
    AtrRatio,
    IntradayIntensity,
    MoneyFlow,
    Reactivity,
    PriceVolumeFit,
    VolumeWeightedMaRatio,
    NormalizedOnBalanceVolume,
    DeltaOnBalanceVolume,
    NormalizedPositiveVolumeIndex,
    NormalizedNegativeVolumeIndex,
    VolumeMomentum,
    Entropy,
    MutualInformation,
    FtiLowpass,
    FtiBestPeriod,
    FtiBestWidth,
    FtiBestFti,
    FtiLargest,
    // Morlet wavelets
    RealMorlet,
    ImagMorlet,
    RealDiffMorlet,
    ImagDiffMorlet,
    RealProductMorlet,
    ImagProductMorlet,
    PhaseMorlet,
    // Daubechies wavelets
    DaubMean,
    DaubMin,
    DaubMax,
    DaubStd,
    DaubEnergy,
    DaubNlEnergy,
    DaubCurve,
    // Additional RSI variants
    CondRsi,
    HiRsi,
    LoRsi,
    ThresholdedRsi,
    // Price momentum
    PriceMomentum,
    // ADX variants
    MinAdx,
    MaxAdx,
    ResidualMinAdx,
    ResidualMaxAdx,
    DeltaAdx,
    AccelAdx,
    // Volatility indicators
    MinPriceVarianceRatio,
    MaxPriceVarianceRatio,
    MinChangeVarianceRatio,
    MaxChangeVarianceRatio,
    DeltaPriceVarianceRatio,
    DeltaChangeVarianceRatio,
    DeltaBollingerWidth,
    PriceSkewness,
    ChangeSkewness,
    PriceKurtosis,
    ChangeKurtosis,
    DeltaPriceSkewness,
    DeltaChangeSkewness,
    DeltaPriceKurtosis,
    DeltaChangeKurtosis,
    DeltaAtrRatio,
    // Volume indicators
    DeltaVolumeMomentum,
    DeltaIntradayIntensity,
    ProductPriceVolume,
    SumPriceVolume,
    DeltaProductPriceVolume,
    DeltaSumPriceVolume,
    DeltaReactivity,
    MinReactivity,
    MaxReactivity,
    DeltaPriceVolumeFit,
    DiffVolumeWeightedMaRatio,
    NegativeVolumeIndex,
    DeltaPositiveVolumeIndex,
    DeltaNegativeVolumeIndex,
    // FTI variants
    FtiMinorLowpass,
    FtiMajorLowpass,
    FtiMinorFti,
    FtiMajorFti,
    FtiLargestPeriod,
    FtiMinorPeriod,
    FtiMajorPeriod,
    FtiCrat,
    FtiMinorBestCrat,
    FtiMajorBestCrat,
    FtiBothBestCrat,
    // Position indicators
    NDayHigh,
    NDayLow,
    NDayNarrower,
    NDayWider,
    NewHigh,
    NewLow,
    NewExtreme,
    OffHigh,
    AboveLow,
    AboveMaBinary,
    AboveMaTrinary,
    RocPositiveBinary,
    RocPositiveTrinary,
    // Persistence
    UpPersist,
    DownPersist,
    // Fit indicators
    CubicFitValue,
    CubicFitError,
    // Target variables (forward-looking)
    HitOrMiss
};

enum class MultiIndicatorId {
    TrendRank,
    CmmaRank,
    TrendMedian,
    CmmaMedian,
    TrendRange,
    CmmaRange,
    TrendIqr,
    CmmaIqr,
    TrendClump,
    CmmaClump,
    Mahalanobis,
    AbsRatio,
    AbsShift,
    Coherence,
    DeltaCoherence,
    JanusIndexMarket,
    JanusIndexDom,
    JanusRawRs,
    JanusFractileRs,
    JanusDeltaFractileRs,
    JanusRss,
    JanusDeltaRss,
    JanusDom,
    JanusDoe,
    JanusRawRm,
    JanusFractileRm,
    JanusDeltaFractileRm,
    JanusRsLeaderEquity,
    JanusRsLaggardEquity,
    JanusRsLeaderAdvantage,
    JanusRsLaggardAdvantage,
    JanusRsPerformanceSpread,
    JanusRmLeaderEquity,
    JanusRmLaggardEquity,
    JanusRmLeaderAdvantage,
    JanusRmLaggardAdvantage,
    JanusRmPerformanceSpread,
    JanusCmaOos,
    JanusLeaderCmaOos,
    JanusOosAvg
};

std::string_view to_string(SingleIndicatorId id);
std::string_view to_string(MultiIndicatorId id);

} // namespace tssb
